### PR TITLE
Modernize setuptools support to use pyproject.toml

### LINKED ISSUE #172: Replace deprecated imp module with importlib
This project uses the [`imp` module](https://docs.python.org/3/library/imp.html) which has been deprecated since Python 3.4 and set for removal in 3.12:

* Raised `PendingDeprecationWarning` since [3.4 (2014)](https://github.com/python/cpython/commit/e4f41deccf94ccc798b1eb1f44657ade66669a60)
* Raised `DeprecationWarning` since [3.5 (2015)](https://github.com/python/cpython/commit/c0d91aff9a3b91307b26e8b7c34dfbf27bbdd43a)
* Updated `DeprecationWarning` to say removal in 3.12 since [3.10 (2021)](https://github.com/python/cpython/commit/dc6d3e1e4c0c1e4b2210edab8fb4762569dc2936)
* Removal planned for [3.12](https://github.com/python/cpython/issues/98040) [(2023)](https://github.com/python/cpython/pull/98573)

Python 3.12 is [set for release on 2023-10-02](https://devguide.python.org/versions/) and this library is one of the [top 5,000 most-downloaded from PyPI](https://hugovk.github.io/top-pypi-packages/).

Please could you upgrade to use `importlib`? The [`imp` docs](https://docs.python.org/3.11/library/imp.html) have suggestions on what to use to replace each function and constant.

### PR DESCRIPTION
**Pull request by mgorny**
Replace the obsolete `setup.py` script and `setup.cfg` configuration file with the modern PEP 621 `pyproject.toml` metadata.  This also implies replacing the custom version/long-description grabbing logic (that is broken with Python 3.12) with the features nowadays built-in in setuptools.

Fixes #172

### CODE REVIEW

**Comment by Knio** [comment]
Thanks! but can you try to get the remaining CI passing? I give up for now.

**Comment by mgorny** [comment]
I can fix 3.12 but FWICS testing against 2.7 is no longer possible with GHA>

**Comment by mgorny** [comment]
Ok, I think that's as far as we can reasonably get. Python < 3.7 is no longer supported by setuptools even.

**Comment by Knio** [comment]
Thanks, this seems to work in CI, but I can't actually build a package locally to publish, as it just makes "UNKNOWN"

```sh
$ python3 -m build --no-isolation
* Getting build dependencies for sdist...
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt
...etc
'```

any ideas?
```sh
$ python3 --version
Python 3.9.2
$ python3 -m build --version
build 1.0.3 (/usr/local/lib/python3.9/dist-packages/build)
```

**Comment by mgorny** [comment]
Thanks!

**Comment by chenrui333** [comment]
Thanks for the PR, any chance cutting off a new release? Thanks!

**Pull request merged**
