### PR TITLE
Add tag() class for create custom elements

### LINKED ISSUE #148: Custom elements
I may be missing something, but there doesn't seem to be a way to construct [custom elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) (or [JSX](https://reactjs.org/docs/introducing-jsx.html))? If not, maybe it could added via an API that looks something like this?

```python
import dominate
dominate.tags.tag('custom-element', 'children', foo='bar')
```

```html
<custom-element foo='bar'> children </custom-element>
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #148

### CODE REVIEW

**Comment by songololo** [comment]
This would be useful, any chance of merging?

**Comment by Knio** [comment]
Thanks, but sorry, I'm not really interested in this. This is very trivial for anyone to write for themselves, not something that most users will use, and I want to keep this library very minimalistic.

Here's another slightly different version which seems shorter and nicer to me (assuming you re-use the same custom element in multiple places):

```python
class custom(dominate.tags.html_tag): pass

custom(foo=1).render()
'<custom foo="1"></custom>'
```

I'd be slightly more willing to take a parameter to `dom_tag`, maybe a `__tagname` similar to `__inline` etc. for the non-reuse case.

**Comment by songololo** [comment]
Thanks @Knio 

Can this example be added to the README?

**Comment by Knio** [comment]
@songololo Sure, but maybe the wiki would be a better place for patterns like this? The readme is fairly long already.

**Pull request closed without merging**
